print("how old are you", end=' ')
age = input()
print("How tall are you", end= ' ')
height = input()
print("How mudh do you weigh?", end=' ')
weight = input ()
print (f"So, you're {age} old, {height} tall and {weight} heavy.")
